### PR TITLE
Folders, distributions lists and more

### PR DESCRIPTION
**Pull request by manens**
* !! Fix a bug when signature name have an accent (python 2.7), replaced str by unicode
  * provide a function to read localconfig.xml informations to ease access to API
  * fix missing valiables in REST client
  * add add_distribution_list_member and remove_distribution_list_member
  * add get_folder and get_folders

### CODE REVIEW

**Comment by JocelynDelalande** [comment]
Thanks a lot for all those contributions, it's appreciated, as well as your attention to docstrings and to providing examples.

But I can't accept your modifications "as is"

- be atomic : 1 PR per feature/bugfix requested
- everything in english language, including commit messages
- rework your history to avoid having in the history having a commit and its revert, it's meaningless for the upstream (use git rebase -i) examples of commits that should be merged is  019c523 +  d350f3a or  4d4f1f6 +  947ece7 , or d1f6d3c +  e8ff3c1
- globally, having twice the  same commit message means that either you should have written better commit message or merget the two commits.
- avoid whitespace modifications like in 947ece7464d138eb2292b0a5c1a3a5be2b79afcc and always put a newline at the end of files (827e5229de281e422d26802a1ff7b07a61c3de0e )

@manens could you please rework those points and submit me several PR ?

In the future, don't hesitate to send me frequent pull requests, it will be easier for both of us :-)

Hopefully we'll be able to publish a new version on pip soon with your edits and a dependency against new version of python-zimbra that integrate the fixes for unicode issues.

Happy hacking :)

**Comment by manens** [comment]
Hi,

I didn't know how to do it clean, I'll look at git rebase.

Best regards,

**Comment by JocelynDelalande** [comment]
> Hi,

I'm happy you don't take it bad :-)

> I didn't know how to do it clean, I'll look at git rebase.


You may also want to look at 

- rebase *-i* to merge or re-order commit
- squash to merge commits
- rebase to stack your edits ontop of the head of my last master (as an alternative to the merge, but that's up to you)
- cherry-pick to pick get just one commit from another branch to your current one.

Lot of `git help` ahead ;)

**Comment by JocelynDelalande** [comment]
@manens thanks

**Pull request closed without merging**
